
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CARD_NAME CARD_TEXT CARD_TYPE MANA_COST POWER TOUGHNESScard : CARD_NAME mana_cost CARD_TYPE CARD_TEXT\n            | CARD_NAME mana_cost CARD_TYPE CARD_TEXT creature_statsmana_cost : MANA_COST\n                 | mana_cost MANA_COSTcreature_stats : POWER TOUGHNESS'
    
_lr_action_items = {'CARD_NAME':([0,],[2,]),'$end':([1,7,8,10,],[0,-1,-2,-5,]),'MANA_COST':([2,3,4,6,],[4,6,-3,-4,]),'CARD_TYPE':([3,4,6,],[5,-3,-4,]),'CARD_TEXT':([5,],[7,]),'POWER':([7,],[9,]),'TOUGHNESS':([9,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'card':([0,],[1,]),'mana_cost':([2,],[3,]),'creature_stats':([7,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> card","S'",1,None,None,None),
  ('card -> CARD_NAME mana_cost CARD_TYPE CARD_TEXT','card',4,'p_card','parser.py',6),
  ('card -> CARD_NAME mana_cost CARD_TYPE CARD_TEXT creature_stats','card',5,'p_card','parser.py',7),
  ('mana_cost -> MANA_COST','mana_cost',1,'p_mana_cost','parser.py',19),
  ('mana_cost -> mana_cost MANA_COST','mana_cost',2,'p_mana_cost','parser.py',20),
  ('creature_stats -> POWER TOUGHNESS','creature_stats',2,'p_creature_stats','parser.py',28),
]
